/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/8.0.2/samples
 */
plugins {
    kotlin("jvm") version "1.8.10"
}

repositories {
    mavenLocal()
    gradlePluginPortal()
    maven { url = uri("https://artifacts.itemis.cloud/repository/maven-mps/") }
    mavenCentral()
}
dependencies {
    testImplementation(kotlin("test"))
}

val platformVersion = file("../platform_version.txt").readText().trim()

kotlin {
    sourceSets {
        val test by getting {
            dependencies {
                api(enforcedPlatform("org.modelix:platform:$platformVersion"))
                implementation("org.modelix:model-server") // to test core version
                implementation("org.modelix:incremental") // to test incremental version
                implementation("org.modelix.mps:build-tools-lib") // to test build-tools version
                implementation("org.modelix.mps:sync-plugin-lib") // to test mps plugins version
            }
        }
    }
}
